his_sistemas/config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  resources :contacts do
    collection do
      put :check_contact
      put :change_user_type
      get :change_user
    end
  end

  resources :articles do
    collection do
      put :destroy_picture
    end
  end

  resources :references do
    collection do
      put :destroy_picture
    end
  end

  resources :services do
    collection do
      put :destroy_picture
    end
  end

  resources :search, only: [:index] do
    collection do
      get :search_articles
    end
  end

  devise_for :users, controllers: {registrations: 'users/registrations', confirmations: 'users/confirmations', passwords: 'users/passwords'}
  resources :home, only: [:index]
  resources :us, only: [:index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: redirect('/home')
end

his_sistemas/app/models/reference.rb
class Reference < ApplicationRecord
	belongs_to :user
	belongs_to :picture , dependent: :destroy

	after_initialize do
		build_picture if new_record? && picture.blank?
	end
	
	accepts_nested_attributes_for :user
	accepts_nested_attributes_for :picture
	validates_associated :picture

	validates_presence_of :title, 		on: [:create, :update]
	validates_presence_of :content, 	on: [:create, :update]
	validates_presence_of :year, 		on: [:create, :update]

end

his_sistemas/app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  before_action :set_reference, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, only: [:edit, :show, :new, :update, :destroy, :destroy_picture]
  before_action :is_admin, only: [:index]
  # GET /references
  # GET /references.json
  def index
    @references = Reference.all
  end

  # GET /references/1
  # GET /references/1.json
  def show
  end

  # GET /references/new
  def new
    flash[:errors] = nil
    @reference=Reference.new
    @@picid=-1;
  end

  # GET /references/1/edit
  def edit
    flash[:errors] = nil
  end

  # POST /references
  # POST /references.json
  def create
    if params[:update_pictures].to_s == "true"
      if @@picid>=0
        @picture=Picture.find(@@picid)
        updated_params=add_pictures(@picture,reference_params['picture_attributes'])
        @picture.update(updated_params)
      else
        @picture=Picture.new(reference_params['picture_attributes'])
        @picture.save
        @@picid=@picture.id
      end
      respond_to do |format|
        format.js { render 'images' }
        format.json { render :new, status: :ok, location: @picture }
      end
    else
      @reference=Reference.new(reference_params)
      if @@picid>=0
        @reference.picture = Picture.find(@@picid)
      end
      respond_to do |format|        
        if @reference.save
          format.html { redirect_to @reference, notice: t('.reference_was_successfully_created') }
          format.json { render :show, status: :created, location: @reference }
        else
          flash[:errors] = @reference.errors.messages.as_json
          format.js { render 'form' }
          format.json { render json: @reference.errors, status: :unprocessable_entity }
        end
      end
    end
    return
  end

  # PATCH/PUT /references/1
  # PATCH/PUT /references/1.json
  def update
    @upictures=params[:update_pictures].to_s
    if @upictures=='true'
      updated_params=add_pictures(@picture,reference_params['picture_attributes'])
      @picture.update(updated_params)
      respond_to do |format|
        format.js { render 'images' }
        format.json { render :edit, status: :ok, location: @picture }
      end
    else
      respond_to do |format|
        if @reference.update(reference_params)
          format.html { redirect_to @reference, notice: t('.reference_was_successfully_updated') }
          format.json { render :show, status: :ok, location: @reference }  
        else
          format.js { render 'form' }
          format.json { render json: @reference.errors, status: :unprocessable_entity }
          flash[:errors] = @reference.errors.messages.as_json
        end
      end
    end
    return
  end

  # DELETE /references/1
  # DELETE /references/1.json
  def destroy
    @reference.destroy
    respond_to do |format|
      format.html { redirect_to references_url, notice: t('.reference_was_successfully_destroyed') }
      format.json { head :no_content }
    end
  end

  def destroy_picture
    @picture = Picture.find(params[:id])
    delete_picture(@picture,params[:index].to_i)
    return
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reference
      @reference = Reference.find(params[:id])
      @picture = @reference.picture
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reference_params
      params.require(:reference).permit(:title, :content, :year, :user_id, {:picture_attributes => [:id,:linked,:files=>[]]})
    end

    def require_admin
      admin_require(references_url)
    end
end

his_sistemas/app/helpers/references_helper.rb
module ReferencesHelper
end

his_sistemas/app/views/references/_form.html.erb
<%= form_with(model: reference, id: 'myform') do |form| %>
 
  <div class="form row">
    <%= form.fields_for :picture do |pic| %>
      <div class="field col-12 form-group">
        <%= pic.hidden_field :linked, value: true %>
        <%= pic.label :files %>
        <%= pic.file_field :files, class: 'form-control lato', multiple: true,accept:".jpg, .jpeg, .gif, .png"%>
        <% if flash[:errors].present?  && flash[:errors].key?('picture.files') %>
          <% flash[:errors]['picture.files'].each do |msg|%>
            <small class="rl lato"><%=msg%></small>                  
          <%end%>
        <%end%>
      </div>
    <%end%>
    <div class="field col-12 form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control lato' %>
      <% if flash[:errors].present?  && flash[:errors].key?('title') %>
        <% flash[:errors]['title'].each do |msg|%>
          <small class="rl lato"><%=msg%></small>                  
        <%end%>
      <%end%>
    </div>

    <div class="field col-12 form-group">
      <%= form.label :content %>
      <%= form.text_area :content, class: 'form-control lato', rows: 5%>
      <% if flash[:errors].present?  && flash[:errors].key?('content') %>
        <% flash[:errors]['content'].each do |msg|%>
          <small class="rl lato"><%=msg%></small>                  
        <%end%>
      <%end%>
    </div>

    <div class="field col-12 form-group">
      <%= form.label :year %>
      <%= form.number_field :year, value: Date.today.year, class: 'form-control lato', min: 1959, max: 2099%>
      <% if flash[:errors].present?  && flash[:errors].key?('year') %>
        <% flash[:errors]['year'].each do |msg|%>
          <small class="rl lato"><%=msg%></small>                  
        <%end%>
      <%end%>
    </div>

    <%= form.hidden_field :user_id, value: current_user.id %>
    
    <%= hidden_field_tag :update_pictures, false%>

    <div class="col-12 actions">
      <%= form.submit t('pub'), class: "btn btn2 lato"%>
    </div>
  </div>
<% end %>

<% content_for :foot do %>
  <%= javascript_include_tag 'preview_images', 'data-turbolinks-track': 'reload' %>
<% end %>

his_sistemas/app/views/references/_images.html.erb
<div class="col-12"><small id="pic-msg" class="rl"></small></div>	
<%@picture.files.each_with_index do |pic,index|%>
	<div class="col-6 col-sm-4 col-md-6 col-lg-4 p-2">
		<div class="cont">
			<%= image_tag(pic.url, class: "img-fluid")%>
			<div class="middle">
				<%= link_to '<i class="fas fa-times"></i>'.html_safe, {controller: 'references', action: 'destroy_picture', index:index, id:@picture}, method: 'put', remote: true%>
			</div>
		</div>
	</div>
<%end%>

his_sistemas/app/views/references/destroy_picture.js.erb
$('#pic-msg').html("Presencia de <u>una</u> imagen es obligatoria")

his_sistemas/app/views/references/edit.html.erb
<%= render "layouts/header_main" %>
<div class="container pb-3">
	<h1 class="py-3 mont"><%= t('.edit_reference')%></h1>
	<div class="row rale mb-3">
		<div class="col-12 col-md-6">
			<div id="showform">
				<%= render 'form', reference: @reference %>
			</div>
			<div class="mt-3">
	      		<%= link_to '<i class="fas fa-angle-left"></i>'.html_safe, references_path, class: "btn btn1", id:"back"%>
			</div>
		</div>
		<div class="col-12 col-md-6">
			<% if @reference.picture.present? %>
				<div class="row" id="result">
					<%=render 'images'%>
				</div>
			<%end%>
		</div>
	</div>
</div>

his_sistemas/app/views/references/form.js.erb
$('#showform').html("<%= escape_javascript(render 'form', reference: @reference) %>")

his_sistemas/app/views/references/images.js.erb
$('#result').html("<%= escape_javascript(render 'images') %>")
$('input[type=file]').val("")

his_sistemas/app/views/references/index.html.erb
<% content_for :head do %>
    <%= stylesheet_link_tag "references", media: 'all', 'data-turbolinks-track': 'reload' %>
<% end %>
<%= render "layouts/header_main" %>
<div class="container pb-3" id="news">
  <% @references.each_with_index do |reference,indice| %>
    <div class="row" id="noticia<%= reference.id %>">
      <% if indice%2!=0 %>
      <div class="info col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
          <div class="contenido">
            <h2 class="mont wl"><%= sanitize reference.title %></h2>
            <p class="fecha pt-2 lato wl"><%= sanitize reference.year %></p>
            <div class="boton pb-2">
                <button type="button" class="btn btn3" data-toggle="modal" data-target="#modalReferencia<%= reference.id %>">Conoce más</button>
            </div> 
            <% if @user_admin %>
            <div class="center">
              <%= link_to '<i class="fas fa-edit"></i>'.html_safe, edit_reference_path(reference), class: "btn btn3 mr-3" %>
              <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, reference, class:"btn btn3" ,method: :delete, data: { confirm: 'Are you sure?' }%>
            </div>
            <%end%>
          </div>
      </div>
      <%end%>
      <div id="slides<%= reference.id %>" class="carousel slide col-12 col-sm-12 col-md-12 col-lg-8 col-xl-8" data-ride="carousel">
        
        <div class="carousel-inner">
          <% reference.picture.files.each do |pic| %>
            <div class="carousel-item">
              <div class="center"><%= image_tag(pic.url,:class=>"imagen", :alt=>"imgNoticia") %></div>
            </div>
          <%end%>
        </div>
        <% if reference.picture.files.length >1 %>
          <ul class="carousel-indicators">
            <% reference.picture.files.each_with_index do |indicator,index|%>
            <li data-target="#slides<%= reference.id %>" data-slide-to='<%= index %>' class=""></li>
            <%end%>           
          </ul>
        
          <a class="carousel-control-prev" href="#slides<%= reference.id %>" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#slides<%= reference.id %>" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
          <%end%>
      </div>
      <% if indice%2==0 %>
      <div class="info col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
          <div class="contenido">
            <h2 class="mont wl"><%= sanitize reference.title %></h2>
            <p class="fecha pt-2 lato wl"><%=  reference.year %></p>
            <div class="boton pb-2">
                <button type="button" class="btn btn3" data-toggle="modal" data-target="#modalReferencia<%= reference.id %>">Conoce más</button>
            </div> 
            <% if @user_admin %>
            <div class="center">
              <%= link_to '<i class="fas fa-edit"></i>'.html_safe, edit_reference_path(reference), class: "btn btn3 mr-3"%>
              <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, reference, class: "btn btn3",data: {toggle: "modal", target: "#confirmar"}%>
            </div>
            <%end%>
          </div>
      </div>
      <%end%>
      <!-- Modal -->
      <div class="modal fade" id="modalReferencia<%= reference.id %>" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title mont" id="modalTitulo"><%= sanitize reference.title %></h5>
            </div>
            <div class="modal-body">
              <p class="textoModal rale jumpline"><%= sanitize reference.content %></p>
              
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn1" data-dismiss="modal">Cerrar</button>
            </div>
          </div>
        </div>
      </div>
      <div class="modal fade" id="confirmar">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Eliminar</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              ¿Está seguro? No se puede recuperar una vez se eliminen los datos.
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn2" data-dismiss="modal"><i class="fas fa-angle-left"></i></button>
              <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, reference, method: :delete, class: "btn btn-danger" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <%end%>
  <% if @user_admin %>
    <%= link_to '<i class="fas fa-plus"></i>'.html_safe, new_reference_path, :class=>"btn btn-circle shadow-lg" %>
  <%end%>
</div>
<% content_for :foot do %>
    <%= javascript_include_tag 'class_adder', 'data-turbolinks-track': 'reload' %>
<% end %>

his_sistemas/app/views/references/new.html.erb
<%= render "layouts/header_main" %>
<div class="container pb-3">
	<h1 class="py-3 mont"><%=t('.new_reference')%></h1>
	<div class="row rale mb-3">
		<div class="col-12 col-md-7 col-lg-6">
			<div id="showform">
				<%= render 'form', reference: @reference %>
			</div>
			<div class="mt-3">
      			<%= link_to '<i class="fas fa-angle-left"></i>'.html_safe, references_path, class: "btn btn1 mt-3"%>
			</div>
		</div>
		<div class="col-12 col-md-6">
			<% if @reference.picture.present? %>
				<div class="row" id="result">
				</div>
			<%end%>
		</div>
	</div>
</div>

his_sistemas/app/views/references/show.html.erb
<%= render "layouts/header_main" %>
<div class="container pt-3">
  <div class="row">
    
    <div class="col-12 col-md-6">
      <strong class="mont"><%=t('title')%></strong>
      <p class="rale">
        <%= sanitize @reference.title %>
      </p>
      <strong class="mont"><%=t('description')%></strong>          
      <div>
        <p class="rale jumpline">
          <%= sanitize @reference.content %>
        </p>
      </div>
      <strong class="mont"><%=t('year') %></strong>
      <p class="rale">
        <%= @reference.year %>
      </p>
      <strong class="mont"><%=t('user')%></strong>
      <p class="rale">
        <%= sanitize @reference.user.contact.name %>
        <%= sanitize @reference.user.contact.lastname %>
      </p>
    </div>
    <div class="col-12 col-md-6">
      <strong class="mont"><%=t('pictures')%></strong>
      <div class="row">
        <% @reference.picture.files.each do |pic| %>
          <div class="col-6 col-sm-4 col-md-6 col-lg-4 p-2">
            <div class="cont">
              <%= image_tag(pic.url,:alt=>"servicio", :class=>"img-fluid") %>
            </div>
          </div>
        </div>
      <%end%>
    </div>
    <div class="col mb-3">
        <%= link_to '<i class="fas fa-edit"></i>'.html_safe, edit_reference_path(@reference), class: 'btn btn1'%>
        <%= link_to '<i class="fas fa-angle-left"></i>'.html_safe, references_path, class: 'btn btn1'%>
    </div>
  </div>
</div>