his_sistemas/config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  resources :contacts do
    collection do
      put :check_contact
      put :change_user_type
      get :change_user
    end
  end

  resources :articles do
    collection do
      put :destroy_picture
    end
  end

  resources :references do
    collection do
      put :destroy_picture
    end
  end

  resources :services do
    collection do
      put :destroy_picture
    end
  end

  resources :search, only: [:index] do
    collection do
      get :search_articles
    end
  end

  devise_for :users, controllers: {registrations: 'users/registrations', confirmations: 'users/confirmations', passwords: 'users/passwords'}
  resources :home, only: [:index]
  resources :us, only: [:index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: redirect('/home')
end

his_sistemas/app/models/service.rb
class Service < ApplicationRecord
  	belongs_to :user
  	belongs_to :picture, dependent: :destroy

	after_initialize do
		build_picture if new_record? && picture.blank?
	end
	
	accepts_nested_attributes_for :user
	accepts_nested_attributes_for :picture, update_only: true
	validates_associated :picture

	validates_presence_of :title, 		on: [:create, :update]
	validates_presence_of :description, on: [:create, :update]
end

his_sistemas/app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, only: [:show, :edit, :new, :update, :destroy, :destroy_picture]
  before_action :is_admin

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    flash[:errors] = nil
    @service=Service.new
    @@picid=-1;
  end

  # GET /services/1/edit
  def edit
    flash[:errors] = nil
  end

  # POST /services
  # POST /services.json
  def create  
    if params[:update_pictures].to_s == "true"
      if @@picid>=0
        @picture=Picture.find(@@picid)
        updated_params=add_pictures(@picture,service_params['picture_attributes'])
        @picture.update(updated_params)
      else
        @picture=Picture.new(service_params['picture_attributes'])
        @picture.save
        @@picid=@picture.id
      end
      respond_to do |format|
        format.js { render 'images' }
        format.json { render :new, status: :ok, location: @picture }
      end
    else
      @service=Service.new(service_params)
      if @@picid>=0
        @service.picture = Picture.find(@@picid)
      end
      respond_to do |format|        
        if @service.save
          format.html { redirect_to @service, notice: t('.service_was_successfully_created') }
          format.json { render :show, status: :created, location: @service }
        else
          flash[:errors] = @service.errors.messages.as_json
          format.js { render 'form' }
          format.json { render json: @service.errors, status: :unprocessable_entity }
        end
      end
    end
    return
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    @upictures=params[:update_pictures].to_s
    if @upictures=='true'
      updated_params=add_pictures(@picture,service_params['picture_attributes'])
      @picture.update(updated_params)
      respond_to do |format|
        format.js { render 'images' }
        format.json { render :edit, status: :ok, location: @picture }
      end
    else
      respond_to do |format|
        if @service.update(service_params)
          format.html { redirect_to @service, notice: t('.service_was_successfully_updated') }
          format.json { render :show, status: :ok, location: @service }  
        else
          format.js { render 'form' }
          format.json { render json: @service.errors, status: :unprocessable_entity }
          flash[:errors] = @service.errors.messages.as_json
        end
      end
    end
    return
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: t('.service_was_successfully_destroyed') }
      format.json { head :no_content }
    end
    return
  end

  def destroy_picture
    @picture = Picture.find(params[:id])
    delete_picture(@picture,params[:index].to_i)
    return
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
      @picture = @service.picture
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:title, :description, :user_id, picture_attributes: [:id,:linked,:files=>[]])
    end

    def require_admin
      admin_require(services_url)
    end
end

his_sistemas/app/helpers/services_helper.rb
module ServicesHelper
end

his_sistemas/app/views/services/_form.html.erb
<%= form_with(model: service, id: 'myform') do |form| %>
  <div class="form row">
    <%= form.fields_for :picture do |pic| %>
      <div class="field col-12 form-group">
        <%= pic.hidden_field :linked, value: true %>
        <%= pic.label :files %>
        <%= pic.file_field :files, class: 'form-control lato', multiple: true, accept:".jpg, .jpeg, .gif, .png"%>
        <% if flash[:errors].present?  && flash[:errors].key?('picture.files') %>
          <% flash[:errors]['picture.files'].each do |msg|%>
            <small class="rl lato"><%=msg%></small>                  
          <%end%>
        <%end%>
      </div>
    <%end%>
    <div class="field col-12 form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control lato'%>
      <% if flash[:errors].present?  && flash[:errors].key?('title') %>
        <% flash[:errors]['title'].each do |msg|%>
          <small class="rl lato"><%=msg%></small>                  
        <%end%>
      <%end%>
    </div>
    <div class="field col-12 form-group">
      <%= form.label :description %>
      <%= form.text_area :description, class: 'form-control lato', rows: 5%>
      <% if flash[:errors].present?  && flash[:errors].key?('description') %>
        <% flash[:errors]['description'].each do |msg|%>
          <small class="rl lato"><%=msg%></small>                  
        <%end%>
      <%end%>
    </div>
    <%= form.hidden_field :user_id, value: current_user.id %>
    <%= hidden_field_tag :update_pictures, false%>


    <div class="col-12 actions">
      <%= form.submit t('pub'), class: "btn btn2 lato"%>
    </div>
  </div>
<% end %>


<% content_for :foot do %>
  <%= javascript_include_tag 'preview_images', 'data-turbolinks-track': 'reload' %>
<% end %>

his_sistemas/app/views/services/_images.html.erb
<div class="col-12"><small id="pic-msg" class="rl"></small></div>	
<%@picture.files.each_with_index do |pic,index|%>
	<div class="col-6 col-sm-4 col-md-6 col-lg-4 p-2">
		<div class="cont">
			<%= image_tag(pic.url, class: "img-fluid")%>
			<div class="middle">
				<%= link_to '<i class="fas fa-times"></i>'.html_safe, {controller: 'services', action: 'destroy_picture', index:index, id:@picture}, method: 'put', remote: true%>
			</div>
		</div>
	</div>
<%end%>

his_sistemas/app/views/services/destroy_picture.js.erb
$('#pic-msg').html("Presencia de <u>una</u> imagen es obligatoria")

his_sistemas/app/views/services/edit.html.erb
<%= render "layouts/header_main" %>
<div class="container pb-3">
	<h1 class="py-3 mont"><%= t('.edit_service')%></h1>
	<div class="row rale mb-3">
		<div class="col-12 col-md-6">
			<div id="showform">
				<%= render 'form', service: @service %>
			</div>
			<div class="mt-3">
	      		<%= link_to '<i class="fas fa-angle-left"></i>'.html_safe, services_path, class: "btn btn1", id:"back"%>
			</div>
		</div>
		<div class="col-12 col-md-6">
			<% if @service.picture.present? %>
				<div class="row" id="result">
					<%=render 'images'%>
				</div>
			<%end%>
		</div>
	</div>
</div>

his_sistemas/app/views/services/form.js.erb
$('#showform').html("<%= escape_javascript(render 'form', service: @service) %>")

his_sistemas/app/views/services/images.js.erb
$('#result').html("<%= escape_javascript(render 'images') %>")
$('input[type=file]').val("")

his_sistemas/app/views/services/index.html.erb
<% content_for :head do %>
    <%= stylesheet_link_tag "services", media: 'all', 'data-turbolinks-track': 'reload' %>
<% end %>
<%= render "layouts/header_main" %>
<section>
  <div class="container pb-3" id="contenedorServicios">
  <% @services.each_with_index do |service, i| %>
    <%if i%3==0%>
      <div class="row justify-content-around">
    <%end%>
        <div class="servicios col-12 col-sm-12 col-md-12 col-lg-3 col-xl-3">
          <% if @user_admin %>
          <div class="pb-5">
          <%else%>
          <div>
          <%end%>
            <div class="center imgServicios">
              <div class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                  <% if service.picture.files.any?%>
                    <% service.picture.files.each do |pic| %>
                      <div class="carousel-item">
                        <%= image_tag(pic.url,:alt=>"servicio", class: "img-fluid") %>
                      </div>
                    <%end%>
                  <%end%>
                </div>
              </div>            
            </div>
            <div class="center infoServicios">
              <div class="titulo">
                <h2 class="mont"><%= sanitize service.title %></h2>
              </div>  
              <div>
                <p class="rale parrafo jumpline"><%= sanitize service.description %></p>
              </div>
            </div>
          </div>

          <% if @user_admin %>
            <div class="mb-3 gg center">
                <%= link_to '<i class="fas fa-edit"></i>'.html_safe, edit_service_path(service), class: "btn btn1" %>
                <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, service,class: "btn btn1",data: {toggle: "modal", target: "#confirmar#{service.id}"}%>
            </div>
            <!-- Modal -->
            <div class="modal fade" id="confirmar<%= service.id %>">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title">Eliminar</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    ¿Está seguro? No se pueden recuperar los datos una vez eliminados.
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn2" data-dismiss="modal"><i class="fas fa-angle-left"></i></button>
                    <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, service, method: :delete, class: "btn btn-danger" %>
                  </div>
                </div>
              </div>
            </div>


          <%end%>
        </div>
    <%if i>0 && i%2==0%>
      </div>
    <%end%>
  <%end%>  
  <% if @user_admin %>
    <%= link_to '<i class="fas fa-plus"></i>'.html_safe, new_service_path, :class=>"btn btn-circle shadow-lg" %>
  <%end%>
  </div>
</section>


<% content_for :foot do %>
  <%= javascript_include_tag 'class_adder', 'data-turbolinks-track': 'reload' %>
<% end %>

his_sistemas/app/views/services/new.html.erb
<%= render "layouts/header_main" %>
<div class="container pb-3">
	<h1 class="py-3 mont"><%=t(".new_service")%></h1>	
	<div class="row rale mb-3">
		<div class="col-12 col-md-7 col-lg-6">
			<div id="showform">
				<%= render 'form', service: @service %>
			</div>
			<div class="mt-3">
	      		<%= link_to '<i class="fas fa-angle-left"></i>'.html_safe, services_path, class: "btn btn1"%>
			</div>
		</div>
		<div class="col-12 col-md-6">
			<% if @service.picture.present? %>
				<div class="row" id="result">
				</div>
			<%end%>
		</div>
	</div>
</div>

his_sistemas/app/views/services/show.html.erb
<%= render "layouts/header_main" %>
<div class="container pt-3">
  <div class="row">
    <div class="col-12 col-md-6">
      <strong class="mont"><%=t('title')%></strong>
      <p class="rale">
        <%= sanitize @service.title %>
      </p>
      <strong class="mont"><%=t('description')%></strong>          
      <div>
        <p class="rale jumpline">
          <%= sanitize @service.description %>
        </p>
      </div>
      <strong class="mont"><%=t('user')%></strong>
      <p class="rale">
        <%= sanitize @service.user.contact.name %>
        <%= sanitize @service.user.contact.lastname %>
      </p>
    </div>
    <div class="col-12 col-md-6">
      <strong class="mont"><%=t('pictures')%></strong>
      <div class="row">
        <% @service.picture.files.each do |pic| %>
          <div class="col-6 col-sm-4 col-md-6 col-lg-4 p-2">
            <div class="cont">
              <%= image_tag(pic.url,:alt=>"servicio", :class=>"img-fluid idk") %>
            </div>
          </div>
        <%end%>
      </div>
    </div>
    <div class="col my-3">
        <%= link_to '<i class="fas fa-edit"></i>'.html_safe, edit_service_path(@service), class: 'btn btn1'%>
        <%= link_to '<i class="fas fa-angle-left"></i>'.html_safe, services_path, class: 'btn btn1'%>
    </div>
  </div>
</div>